### ISSUE TITLE
Get node folder

### ISSUE THREAD

**Issue by Heavywavez** [RayViljoen/grunt-sitemap#38]
Why if i set the homepage my URL, it will add all node_modules???

**Comment by RayViljoen** [comment]
Because the 
![rayviljoen_grunt-sitemap__grunt_plugin_for_generating_sitemaps](https://cloud.githubusercontent.com/assets/719761/24797465/a0b3bf92-1b91-11e7-8fdd-73a17d7f8c0a.png)

You should probably move your site's public directory to it's own dir, but failing that, you'll have to excude `/node_modules`.
